<a href="https://colab.research.google.com/github/RapaDewan/Natural-Language-Process--NLP-/blob/main/CB_NLP_VID_15/CB_NLP_VID_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
spam_csv= 'https://raw.githubusercontent.com/codebasics/nlp-tutorials/refs/heads/main/9_bag_of_words/spam.csv'
df= pd.read_csv(spam_csv)
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.shape

(5572, 2)

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df['spam']= df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head(), df.shape

(  Category                                            Message  spam
 0      ham  Go until jurong point, crazy.. Available only ...     0
 1      ham                      Ok lar... Joking wif u oni...     0
 2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
 3      ham  U dun say so early hor... U c already then say...     0
 4      ham  Nah I don't think he goes to usf, he lives aro...     0,
 (5572, 3))

##Train test split


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

2131            Later i guess. I needa do mcat study too.
5216                        I am late. I will be there at
309     TheMob> Check out our newest selection of cont...
5018    Dear 0776xxxxxxx U've been invited to XCHAT. T...
Name: Message, dtype: object

In [14]:
y_train.shape

(4457,)

In [15]:
y_test.shape

(1115,)

In [16]:
y_train[:4]

2131    0
5216    0
309     1
5018    1
Name: spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

##Create bag of words representation using CountVectorizer


In [18]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7685 sparse matrix of type '<class 'numpy.int64'>'
	with 59483 stored elements in Compressed Sparse Row format>

In [19]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
X_train_cv.shape

(4457, 7685)

In [21]:
v.get_feature_names_out()[1771]

'cheap'

In [22]:
v.vocabulary_


{'later': 4045,
 'guess': 3309,
 'needa': 4717,
 'do': 2399,
 'mcat': 4401,
 'study': 6508,
 'too': 6932,
 'am': 953,
 'late': 4042,
 'will': 7464,
 'be': 1294,
 'there': 6796,
 'at': 1133,
 'themob': 6789,
 'check': 1776,
 'out': 5007,
 'our': 5004,
 'newest': 4749,
 'selection': 5975,
 'of': 4889,
 'content': 2012,
 'games': 3105,
 'tones': 6923,
 'gossip': 3240,
 'babes': 1209,
 'and': 980,
 'sport': 6373,
 'keep': 3932,
 'your': 7652,
 'mobile': 4533,
 'fit': 2907,
 'funky': 3083,
 'text': 6749,
 'wap': 7335,
 'to': 6895,
 '82468': 669,
 'dear': 2215,
 '0776xxxxxxx': 32,
 've': 7211,
 'been': 1314,
 'invited': 3757,
 'xchat': 7590,
 'this': 6818,
 'is': 3775,
 'final': 2880,
 'attempt': 1145,
 'contact': 2008,
 'txt': 7058,
 'chat': 1766,
 '86688': 700,
 '150p': 304,
 'msgrcvdhg': 4609,
 'suite342': 6557,
 '2lands': 397,
 'row': 5812,
 'w1j6hl': 7289,
 'ldn': 4065,
 '18yrs': 322,
 'then': 6790,
 'ur': 7155,
 'sis': 6161,
 'how': 3555,
 'whatsup': 7424,
 'dont': 2436,
 'want': 7330,

In [23]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
np.where(X_train_np[0]!=0)

(array([2399, 3309, 4045, 4401, 4717, 6508, 6932]),)

In [28]:
#X_train[:4][1579]


In [29]:
X_train_np[0][1771]


0

##Train the naive bayes model


In [30]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [31]:
X_test_cv = v.transform(X_test)


##Evaluate Performance


In [32]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       971
           1       0.98      0.90      0.93       144

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [33]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [34]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [35]:
clf.fit(X_train, y_train)


Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [36]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       971
           1       0.98      0.90      0.93       144

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

